// Package srv provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package srv

import (
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for UpdateUserRequestGender.
const (
	Female UpdateUserRequestGender = "female"
	Male   UpdateUserRequestGender = "male"
)

// CreateUserRequest defines model for CreateUserRequest.
type CreateUserRequest struct {
	Emails     *[]string `json:"emails,omitempty"`
	FirstName  string    `json:"first_name"`
	Patronymic *string   `json:"patronymic,omitempty"`
	Surname    string    `json:"surname"`
}

// ListUsersResponse defines model for ListUsersResponse.
type ListUsersResponse struct {
	Total int    `json:"total"`
	Users []User `json:"users"`
}

// UpdateUserRequest defines model for UpdateUserRequest.
type UpdateUserRequest struct {
	Age         *int                     `json:"age,omitempty"`
	Emails      *[]string                `json:"emails,omitempty"`
	Gender      *UpdateUserRequestGender `json:"gender,omitempty"`
	Name        *string                  `json:"name,omitempty"`
	Nationality *string                  `json:"nationality,omitempty"`
	Patronymic  *string                  `json:"patronymic,omitempty"`
	Surname     *string                  `json:"surname,omitempty"`
}

// UpdateUserRequestGender defines model for UpdateUserRequest.Gender.
type UpdateUserRequestGender string

// User defines model for User.
type User struct {
	Age         int                `json:"age"`
	Emails      *[]string          `json:"emails,omitempty"`
	Gender      string             `json:"gender"`
	Id          openapi_types.UUID `json:"id"`
	Name        string             `json:"name"`
	Nationality string             `json:"nationality"`
	Patronymic  string             `json:"patronymic"`
	Surname     string             `json:"surname"`
}

// ListUsersParams defines parameters for ListUsers.
type ListUsersParams struct {
	Limit  int `form:"limit" json:"limit"`
	Offset int `form:"offset" json:"offset"`
}

// AddFriendParams defines parameters for AddFriend.
type AddFriendParams struct {
	FriendId int64 `form:"friend_id" json:"friend_id"`
}

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = CreateUserRequest

// UpdateUserJSONRequestBody defines body for UpdateUser for application/json ContentType.
type UpdateUserJSONRequestBody = UpdateUserRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all users
	// (GET /users)
	ListUsers(c *gin.Context, params ListUsersParams)
	// Create a user
	// (POST /users)
	CreateUser(c *gin.Context)
	// Search persons by surname
	// (GET /users/surname/{surname})
	SearchUsersBySurname(c *gin.Context, surname string)
	// Update a person
	// (PUT /users/{id})
	UpdateUser(c *gin.Context, id int64)
	// List friends of a user
	// (GET /users/{id}/friends)
	ListFriends(c *gin.Context, id int64)
	// Add a friend
	// (POST /users/{id}/friends)
	AddFriend(c *gin.Context, id int64, params AddFriendParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ListUsers operation middleware
func (siw *ServerInterfaceWrapper) ListUsers(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListUsersParams

	// ------------- Required query parameter "limit" -------------

	if paramValue := c.Query("limit"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument limit is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "limit", c.Request.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "offset" -------------

	if paramValue := c.Query("offset"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument offset is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "offset", c.Request.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter offset: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListUsers(c, params)
}

// CreateUser operation middleware
func (siw *ServerInterfaceWrapper) CreateUser(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateUser(c)
}

// SearchUsersBySurname operation middleware
func (siw *ServerInterfaceWrapper) SearchUsersBySurname(c *gin.Context) {

	var err error

	// ------------- Path parameter "surname" -------------
	var surname string

	err = runtime.BindStyledParameterWithOptions("simple", "surname", c.Param("surname"), &surname, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter surname: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SearchUsersBySurname(c, surname)
}

// UpdateUser operation middleware
func (siw *ServerInterfaceWrapper) UpdateUser(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateUser(c, id)
}

// ListFriends operation middleware
func (siw *ServerInterfaceWrapper) ListFriends(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListFriends(c, id)
}

// AddFriend operation middleware
func (siw *ServerInterfaceWrapper) AddFriend(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params AddFriendParams

	// ------------- Required query parameter "friend_id" -------------

	if paramValue := c.Query("friend_id"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument friend_id is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "friend_id", c.Request.URL.Query(), &params.FriendId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter friend_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AddFriend(c, id, params)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/users", wrapper.ListUsers)
	router.POST(options.BaseURL+"/users", wrapper.CreateUser)
	router.GET(options.BaseURL+"/users/surname/:surname", wrapper.SearchUsersBySurname)
	router.PUT(options.BaseURL+"/users/:id", wrapper.UpdateUser)
	router.GET(options.BaseURL+"/users/:id/friends", wrapper.ListFriends)
	router.POST(options.BaseURL+"/users/:id/friends", wrapper.AddFriend)
}
