openapi: 3.0.3
info:
  title: Person API
  version: 1.0.0
  description: API for managing users and their friendships
servers:
  - url: http://localhost:8080
    description: Local development server
paths:
  /users:
    get:
      summary: List all users
      operationId: listUsers
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
          required: true
        - in: query
          name: offset
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: List of persons
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListUsersResponse'
    post:
      summary: Create a user
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
      responses:
        '201':
          description: User created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid request
  /users/{id}:
    put:
      summary: Update a person
      operationId: updateUser
      parameters:
        - name: id
          in: path
          schema:
            type: integer
            format: int64
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserRequest'
      responses:
        '200':
          description: Person updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: Person not found
  /users/surname/{surname}:
    get:
      summary: Search persons by surname
      operationId: searchUsersBySurname
      parameters:
        - name: surname
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of persons with matching surname
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
  /users/{id}/friends:
    get:
      summary: List friends of a user
      operationId: listFriends
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: List of friends
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    post:
      summary: Add a friend
      operationId: addFriend
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: friend_id
          in: query
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '201':
          description: Friend added
        '400':
          description: Invalid request
        '404':
          description: Person or friend not found
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        surname:
          type: string
        patronymic:
          type: string
        gender:
          type: string
        nationality:
          type: string
        age:
          type: integer
        emails:
          type: array
          items:
            type: string
      required:
        - id
        - name
        - surname
        - patronymic
        - gender
        - nationality
        - age
    CreateUserRequest:
      type: object
      properties:
        first_name:
          type: string
        surname:
          type: string
        patronymic:
          type: string
        emails:
          type: array
          items:
            type: string
      required:
        - first_name
        - surname
    CreateFullUserRequest:
      type: object
      properties:
        first_name:
          type: string
        surname:
          type: string
        patronymic:
          type: string
        age: 
          type: number
          format: integer
        nationality:
          type: string
        emails:
          type: array
          items:
            type: string
        gender:
          type: string
          enum:
            - male
            - female
    UpdateUserRequest:
      type: object
      properties:
        name:
          type: string
        surname:
          type: string
        patronymic:
          type: string
        age:
          type: integer
        nationality:
          type: string
        gender:
          type: string
          enum: 
            - male
            - female
        emails:
          type: array
          items:
            type: string
    ListUsersResponse:
      type: object
      properties:
        users:
          type: array
          items:
            $ref: '#/components/schemas/User'
        total:
          type: integer
      required:
       - users
       - total